### ISSUE TITLE
8-digit hex colors

### ISSUE THREAD

**Issue by Mottie** [sindresorhus/rgb-hex-cli#1]
Webkit is already providing 8-digit hex colors in the development panel for colors with an alpha channel even though the [CSS level 4 color module](https://drafts.csswg.org/css-color/#hex-notation) is still in the draft stage. Please consider including support for this channel.

**Comment by sindresorhus** [comment]
Happy to accept a pull request, but not something I personally need. Would need to be supported in the `rgb-hex` module first.
